#!/bin/sh
set -e

SYSLOGNG_OPTS=""

[ -r /etc/default/rsyslog ] && . /etc/default/rsyslog

case "x$CONSOLE_LOG_LEVEL" in
  x[1-8])
    dmesg -n $CONSOLE_LOG_LEVEL
    ;;
  x)
    ;;
  *)
    echo "CONSOLE_LOG_LEVEL is of unaccepted value."
    ;;
esac

if [ ! -e /dev/xconsole ]
then
  mknod -m 640 /dev/xconsole p
fi

exec rsyslogd -f /etc/rsyslog.conf -i /var/run/rsyslog.pid $SYSLOGNG_OPTS
